version: '3.4'

services:
  adapter:
    image: 127.0.0.1:5001/src
    build: src/
    network_mode: host
    environment:
      # MQTT config
      MQTT_BROKER: "192.168.48.71"
      MQTT_SUBSCRIBED_TOPICS: "prusa3d/#,sensorpi/#,octoprint/#"
      # Panta Rhei configuration
      CLIENT_NAME: "mqtt-adapter"
      SYSTEM_NAME: "at.srfg.iot.dtz"
      SENSORTHINGS_HOST: "192.168.48.71:8082"
      BOOTSTRAP_SERVERS: "192.168.48.71:9092,192.168.48.71:9093,192.168.48.71:9094"
    deploy:
      placement:
        constraints: [node.role == worker]
      resources:
        limits:
          cpus: "1"
          memory: 4G
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
