version: '3.3'

services:
  mqtt-broker:
    image: eclipse-mosquitto:1.5
#    env_file:
#      - .env
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /mnt/glusterfs/dtz/mqtt/config:/mosquitto/config
      - /mnt/glusterfs/dtz/mqtt/data:/mosquitto/data
      - /mnt/glusterfs/dtz/mqtt/log:/mosquitto/log
    networks:
      - mqtt-network
    deploy:
      placement:
        constraints: [node.role == worker]
      resources:
        limits:
          cpus: "1"
          memory: 2G
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any

# Network
networks:
  mqtt-network:

